enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# RVX

[YoutubeRVXinotia00]
enabled = true
build-mode = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "inotia00ReVanced"
patcher-args = "--legacy-options options.json"

[YTMusicRVXinotia00]
enabled = true
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "inotia00ReVanced"
patcher-args = "--legacy-options options.json"

[RedditRVXinotia00]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "inotia00ReVanced"
included-patches = "'Change package name' 'Custom branding name for Reddit'"
patcher-args = "--legacy-options options.json"